events {}
http {
    server {
        listen 80;
        # Root for Frontend
        location / {
            proxy_pass http://web:3000;
        }
        # Root for Backend APIs
        location /api/ {
            proxy_pass http://server:4000;
        }
    }
}